name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: 'Improvements'
    labels:
      - 'perf'
      - 'refactor'
  - title: 'Tests'
    labels:
      - 'tests'
      - 'testing'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
      - 'revert'
  - title: '🧰 Maintenance'
    labels:
      - 'docs'
      - 'chore'
      - 'style'
      - 'build'
      - 'chores'
      - 'ci'
change-template: '- [ ] #$NUMBER $TITLE - @$AUTHOR $DESC '
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES
branches:
  - main
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feat\/.+/'
      - '/refactor\/.+/'